server:
  port: 8888

spring:
  application:
    name: configserver

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yemza/qcmconfig.git/blob/main/
          timeout: 5
          clone-on-start: true
          force-pull: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : "http://${eureka.instance.hostname}:8761/eureka/"
  instance:
    prefer-ip-address: true
    hostname: localhost
